add_newline = false

[aws]
disabled=false
format = '[$symbol($profile)](green)'
symbol = "  "
[aws.region_aliases]
eu-central-1 = "eu"

[cmd_duration]
disabled=true
min_time = 500
format = "took [$duration ](bold yellow)"

[directory]
truncation_length = 3
truncation_symbol = "…/"
home_symbol = "~"

[git_branch]
format = "[$symbol$branch ]($style)"

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
stashed = false

[python]
format='[${symbol}$version (\($virtualenv\)) ]($style)'
symbol = " "
detect_extensions = []
detect_files = []

[docker_context]
disabled=true

[time]
disabled = false
format = "[$time]($style) "
