add_newline = false

[aws]
disabled=true
format = '[$symbol($profile )(\($region\) )]($style)'
symbol = "  "
[aws.region_aliases]
eu-central-1 = "eu"

[cmd_duration]
disabled=true
min_time = 500
format = "took [$duration ](bold yellow)"

[directory]
truncation_length = 3
truncation_symbol = "…/"
home_symbol = "~"

[git_branch]
format = "[$symbol$branch ]($style)"

[python]
format='[${symbol}$version (\($virtualenv\)) ]($style)'
symbol = " "
